import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fdf9f3",
        "surface-dim": "#dddad4",
        "surface-bright": "#fdf9f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f3ed",
        "surface-container": "#f1ede7",
        "surface-container-high": "#ebe8e2",
        "surface-container-highest": "#e6e2dc",
        "on-surface": "#1c1c18",
        "on-surface-variant": "#514442",
        "inverse-surface": "#31302d",
        "inverse-on-surface": "#f4f0ea",
        outline: "#847371",
        "outline-variant": "#d6c2bf",
        "surface-tint": "#82524c",
        primary: "#82524c",
        "on-primary": "#ffffff",
        "primary-container": "#c98f88",
        "on-primary-container": "#522925",
        "inverse-primary": "#f6b7af",
        secondary: "#8a4e41",
        "on-secondary": "#ffffff",
        "secondary-container": "#feb1a0",
        "on-secondary-container": "#794135",
        tertiary: "#695c56",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#aa9a93",
        "on-tertiary-container": "#3d322d",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad5",
        "primary-fixed-dim": "#f6b7af",
        "on-primary-fixed": "#33110d",
        "on-primary-fixed-variant": "#673b36",
        "secondary-fixed": "#ffdad3",
        "secondary-fixed-dim": "#ffb4a4",
        "on-secondary-fixed": "#370e06",
        "on-secondary-fixed-variant": "#6d372c",
        "tertiary-fixed": "#f1dfd7",
        "tertiary-fixed-dim": "#d4c3bc",
        "on-tertiary-fixed": "#231a15",
        "on-tertiary-fixed-variant": "#50443f",
        background: "#fdf9f3",
        "on-background": "#1c1c18",
        "surface-variant": "#e6e2dc",
      },
      fontFamily: {
        display: ["var(--font-playfair)", "serif"],
        headline: ["var(--font-playfair)", "serif"],
        body: ["var(--font-dm-sans)", "sans-serif"],
        sans: ["var(--font-dm-sans)", "sans-serif"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "120px",
      },
      borderRadius: {
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        ambient: "0 12px 32px rgba(62, 51, 46, 0.04)",
      },
      animation: {
        "fade-in": "fadeIn 1.2s ease-out forwards",
        "slide-up": "slideUp 1s ease-out forwards",
        pulse: "pulse 1.5s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
