import { PrismaClient, KnowledgeDomain, KnowledgeType, SafetyClass, EvidenceLevel, RelationType } from '@prisma/client';

const prisma = new PrismaClient();

const seedKnowledgeNodes: any[] = [
  // SELF (13 nodes)
  {
    id: 'SELF-001',
    domain: KnowledgeDomain.SELF,
    category: 'self_agency',
    title: '我是自己人生的主角',
    titleEn: 'I am the protagonist of my own life',
    coreIdea: '人生最重要的责任首先是对自己负责，而不是把人生的方向交给别人。',
    coreIdeaEn: 'The most important responsibility in life is to yourself, not handing your direction over to others.',
    mentorInterpretation: '重要的不是控制所有结果，而是尽可能掌握自己的选择、行动和边界。',
    applicationContexts: ['人生决策', '职业选择', '关系边界'],
    reflectionQuestions: ['这件事情里，什么是你真正能够决定的？', '如果不考虑别人的期待，你会怎么选择？'],
    counterpoints: ['对自己负责不等于孤立无援。接受帮助和利用资源也是自我负责的一部分。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 核心信条',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-002',
    domain: KnowledgeDomain.SELF,
    category: 'self_worth',
    title: '自我价值从内部建立',
    titleEn: 'Build self-worth from within',
    coreIdea: '外在认可可以提供反馈，但如果把它当作衡量自我价值的唯一标准，容易在评价波动中失去稳定感。',
    coreIdeaEn: 'External validation can offer feedback, but relying on it as the sole measure of self-worth makes stability fragile.',
    mentorInterpretation: '真正的自我价值不是“没有人批评我”，而是“即使不被选择、不被赞美，我依然知道自己的价值有根基”。',
    applicationContexts: ['被否定后的自我怀疑', '恋爱中价值感低落', '职业受挫'],
    reflectionQuestions: ['如果今天没有人表扬你，你觉得自己仍然有价值吗？', '你把多少自我价值交给了外界评判？'],
    counterpoints: ['完全忽视外界反馈也可能让人固执。健康的状态是：外界反馈是信息，不是判决书。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 自我价值',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-003',
    domain: KnowledgeDomain.SELF,
    category: 'self_worth',
    title: '不把自我价值交给外界评价',
    titleEn: 'Do not base self-worth solely on external judgment',
    coreIdea: '外界评价可以作为反馈，但不应该成为判断自己是否值得被尊重和喜欢的唯一标准。',
    coreIdeaEn: 'External feedback can inform you, but it should not be the sole measure of your worth.',
    reflectionQuestions: ['你现在最在意谁的评价？', '如果暂时没有这个人的评价，你怎么看待自己？'],
    counterpoints: ['完全屏蔽外界评价可能让人失去改进的镜子。关键是把评价当参考，而非判决书。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 自我价值',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-004',
    domain: KnowledgeDomain.SELF,
    category: 'independence',
    title: '独立是经济、能力与精神的综合状态',
    titleEn: 'Independence spans economy, capability, and spirit',
    coreIdea: '经济能力、生活能力与精神自主共同构成一个人的独立基础，缺少任何一项都会让选择空间受限。',
    coreIdeaEn: 'Economic power, life capability, and mental autonomy together form the foundation of independence.',
    mentorInterpretation: '独立不是“谁都不需要”，而是“我有能力选择靠近谁、离开谁、依靠谁”。',
    applicationContexts: ['离开关系前的准备', '职业转型', '家庭压力'],
    reflectionQuestions: ['如果明天必须独自生活一年，你最担心哪方面？', '你现在的选择里，有多少是出于“必须”，多少是出于“愿意”？'],
    counterpoints: ['强调独立不等于否认互相依赖。人类天然需要连接，独立是为了让依赖成为选择，而不是被迫。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 独立',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-005',
    domain: KnowledgeDomain.SELF,
    category: 'environment',
    title: '环境塑造人',
    titleEn: 'Environment shapes the self',
    coreIdea: '所处的环境会深刻影响一个人的行为模式、情绪、机会和认知标准。',
    coreIdeaEn: 'The environment deeply shapes behavior, emotions, opportunities, and cognitive standards.',
    mentorInterpretation: '改变环境不是逃避自己，而是主动选择更容易成为自己想要成为的人的外部条件。',
    applicationContexts: ['选择城市', '换工作', '改变社交圈', '结束消耗性关系'],
    reflectionQuestions: ['你现在最常相处的五个人，反映了你正在成为什么样的人？', '如果你可以改变一个环境因素，会是什么？'],
    counterpoints: ['环境不是决定因素。同样的环境可以养育不同的人，最终成长仍依赖个人选择和行动。'],
    knowledgeType: KnowledgeType.observation,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.OBSERVATION,
    sourceReference: '女性成长导师·知识蒸馏 — 环境',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-006',
    domain: KnowledgeDomain.SELF,
    category: 'environment',
    title: '圈子决定认知水位',
    titleEn: 'Your circle sets your cognitive waterline',
    coreIdea: '长期相处的人会潜移默化地塑造一个人的标准、眼界和自我期许。',
    coreIdeaEn: 'Long-term companions subtly shape one\'s standards, horizons, and self-expectations.',
    mentorInterpretation: '换圈子不是势利，而是有意识地选择能够互相激发成长的关系场。',
    applicationContexts: ['职业发展', '个人成长', '创业'],
    reflectionQuestions: ['你的圈子里有没有人做到了你真正想做的事？', '当你表达一个目标时，周围的人一般如何反应？'],
    counterpoints: ['“向上社交”如果变成功利交换，反而容易让人孤立。真诚和价值互换同样重要。'],
    knowledgeType: KnowledgeType.observation,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.OBSERVATION,
    sourceReference: '女性成长导师·知识蒸馏 — 圈子',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-007',
    domain: KnowledgeDomain.SELF,
    category: 'growth',
    title: '精进自己',
    titleEn: 'Keep investing in yourself',
    coreIdea: '长期投资自己的能力，是建立独立性和选择权的重要方式。',
    coreIdeaEn: 'Long-term investment in your own abilities is key to building independence and options.',
    mentorInterpretation: '不需要一次解决人生所有问题，只需要持续增加自己的能力、知识和资源。',
    counterpoints: ['自我投资也需要方向。盲目学习而不解决真实问题，可能变成“自我感动式努力”。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 核心信条',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-008',
    domain: KnowledgeDomain.SELF,
    category: 'emotional_regulation',
    title: '反刍不如行动',
    titleEn: 'Rumination is not action',
    coreIdea: '反复思考不可控的事情会消耗大量精力，把焦点拉回事实、目标和可控行动上会更有效。',
    coreIdeaEn: 'Repeatedly dwelling on uncontrollable things drains energy; focus on facts, goals, and controllable actions.',
    mentorInterpretation: '不是压抑情绪，而是给情绪一个边界：允许自己担心，但不让担心无限循环。',
    applicationContexts: ['焦虑', '失眠', '分手后反复回想', '工作失误后的自责'],
    reflectionQuestions: ['你反复想的事情里，有多少是你可以控制的？', '如果现在必须采取一个最小行动，那会是什么？'],
    counterpoints: ['有些问题确实需要深思熟虑。行动不能替代必要的反思和战略规划。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 反刍',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-009',
    domain: KnowledgeDomain.SELF,
    category: 'emotional_regulation',
    title: '具体化焦虑',
    titleEn: 'Make anxiety specific',
    coreIdea: '焦虑往往来自模糊的威胁感，把担心的事情具体化后，往往能区分出真实风险与想象放大。',
    coreIdeaEn: 'Anxiety often comes from vague threats; specifying the worry helps separate real risk from imagined amplification.',
    mentorInterpretation: '当用户说“我很焦虑”时，先帮她把抽象情绪落实到一个具体情境、具体事件和具体结果上。',
    applicationContexts: ['焦虑处理', '决策前恐惧', '公开演讲', '职业变动'],
    reflectionQuestions: ['你最担心的那一件事，具体是什么？', '如果它真的发生，你接下来会怎么做？'],
    counterpoints: ['过度具体化也可能让人陷入灾难化想象。具体化的目的是获得掌控感，而不是罗列所有最坏情况。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 焦虑与具体',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-010',
    domain: KnowledgeDomain.SELF,
    category: 'emotional_regulation',
    title: '情绪可以被看见，但不必主导决定',
    titleEn: 'Emotions can be felt without driving decisions',
    coreIdea: '情绪是重要的信息，但强烈情绪出现时不一定适合立即做重大决定。',
    coreIdeaEn: 'Emotions carry information, but intense emotions are not always the right basis for major decisions.',
    counterpoints: ['情绪不是敌人。完全压抑情绪会切断重要信号。关键是让情绪被听见，但不自动掌控方向。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 情绪管理',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-011',
    domain: KnowledgeDomain.SELF,
    category: 'boundaries',
    title: '敢于拒绝',
    titleEn: 'The ability to say no',
    coreIdea: '拒绝不合理的要求不是冷漠，而是保护时间、精力和边界的重要能力。',
    coreIdeaEn: 'Saying no to unreasonable requests is not coldness; it protects time, energy, and boundaries.',
    mentorInterpretation: '很多女性在“拒绝”时伴随强烈愧疚，需要意识到：拒绝一件事不等于拒绝一个人。',
    applicationContexts: ['职场额外任务', '家庭过度索取', '朋友借钱', '亲密关系中的越界'],
    reflectionQuestions: ['你上一次说“不”是什么时候？感受如何？', '你害怕拒绝时，真正害怕的是什么？'],
    counterpoints: ['拒绝也需要成本。每一次拒绝都可能影响关系，关键是判断哪些边界值得维护。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 边界',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-013',
    domain: KnowledgeDomain.SELF,
    category: 'boundaries',
    title: '建立清晰边界',
    titleEn: 'Set clear boundaries',
    coreIdea: '边界不是控制别人，而是明确自己接受什么、不接受什么，以及越界后自己会采取什么行动。',
    coreIdeaEn: 'Boundaries are about clarifying what you will and will not accept, not controlling others.',
    applicationContexts: ['关系', '职场', '家庭'],
    reflectionQuestions: ['你的边界被触碰时，你会怎么做？'],
    counterpoints: ['边界过于僵硬也可能隔离亲密。健康边界是灵活而有底的，不是一堵墙。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 边界',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'SELF-020',
    domain: KnowledgeDomain.SELF,
    category: 'independence',
    title: '经济能力增加人生选择权',
    titleEn: 'Economic capability expands life choices',
    coreIdea: '经济能力可以增加一个人在关系、职业和生活中的选择空间。',
    coreIdeaEn: 'Financial capability expands a person’s choices in relationships, career, and life.',
    mentorInterpretation: '经济独立不是衡量女性价值的唯一标准，但经济能力往往会直接影响一个人的选择自由。',
    counterpoints: ['经济能力不是人生的全部。把赚钱当作唯一目标，可能牺牲关系、健康和意义感。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 经济独立',
    sourceType: 'user_provided_knowledge_base',
  },
  // RELATIONSHIPS (13 nodes)
  {
    id: 'REL-001',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'reciprocity',
    title: '关系是双向投入',
    titleEn: 'Relationships are mutual investment',
    coreIdea: '健康关系存在相互需求和投入，但不能把人的价值完全简化成交易价值。',
    coreIdeaEn: 'Healthy relationships involve mutual needs and investment, but human value should not be reduced to transactional worth.',
    mentorInterpretation: '一方长期单方面付出，关系结构往往难以持续。但“交换”不是算计，而是彼此都感受得到被看见。',
    applicationContexts: ['恋爱早期', '长期关系', '友谊'],
    reflectionQuestions: ['在这段关系里，你和对方的投入大致平衡吗？', '如果去掉物质和情绪付出，你还愿意和这个人相处吗？'],
    counterpoints: ['不同人生阶段投入可能不平等。健康关系允许阶段性的不对等，但不能长期只有一方维系。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 交换',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-002',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'compatibility',
    title: '长期关系需要价值匹配',
    titleEn: 'Long-term relationships require value compatibility',
    coreIdea: '长期关系不仅取决于感情强度，还取决于价值观、生活方式、责任和目标是否能够长期协调。',
    coreIdeaEn: 'Long-term relationships depend not only on emotion, but also on aligned values, lifestyles, responsibilities, and goals.',
    reflectionQuestions: ['你们真正重要的长期目标一致吗？', '哪些差异可以协商？', '哪些差异可能持续消耗你？'],
    counterpoints: ['没有两个人完全匹配。关键在于双方是否愿意为差异持续沟通和调整，而不是寻找“完美匹配”。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 价值匹配',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-003',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'expectations',
    title: '期待需要与现实对齐',
    titleEn: 'Align expectations with reality',
    coreIdea: '对伴侣、关系或自己的期待如果脱离现实，容易反复失望并产生冲突。',
    coreIdeaEn: 'Expectations of partners, relationships, or oneself that are detached from reality easily lead to repeated disappointment and conflict.',
    mentorInterpretation: '降低不现实期待不等于降低底线，而是把期待建立在可观察的行为和一致的事实上。',
    applicationContexts: ['新婚磨合', '长期关系倦怠', '相亲初期'],
    reflectionQuestions: ['你的期待是基于对方真实的样子，还是你希望他成为的样子？', '哪些期待其实是你自己人生课题的投射？'],
    counterpoints: ['过低期待可能让人停留在不合适的关系里。期待管理是校准，不是自我压抑。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 预期管理',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-005',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'independence',
    title: '保持关系之外的自我',
    titleEn: 'Maintain a self outside the relationship',
    coreIdea: '亲密关系应该成为人生的一部分，而不应该成为人生的全部。',
    coreIdeaEn: 'Intimacy should be part of life, not the whole of it.',
    counterpoints: ['强调独立不等于在关系中保持疏离。真正的亲密需要一定融合，关键是不过度依赖。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 关系独立',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-006',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'investment',
    title: '不要在早期超额投入',
    titleEn: 'Do not overinvest early',
    coreIdea: '关系还没有建立信任和长期基础时，投入不应超过自己能够承受失去的范围。',
    coreIdeaEn: 'Before trust and long-term foundation are established, investment should not exceed what one can afford to lose.',
    mentorInterpretation: '过早、过多投入容易把“我已经付出很多”当成继续的理由，而不是基于真实匹配度的判断。',
    applicationContexts: ['暧昧期', '相亲', '新恋情'],
    reflectionQuestions: ['如果这段关系明天结束，你的投入会让你难以抽身吗？', '你的投入是因为喜悦，还是因为害怕失去？'],
    counterpoints: ['过度设防也可能让人难以建立真诚关系。关键是投入与阶段匹配，而不是完全不投入。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 投入与阶段',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-007',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'behavior',
    title: '行动比承诺更值得观察',
    titleEn: 'Actions are more reliable than promises',
    coreIdea: '判断关系时，可以同时观察对方说了什么以及长期实际做了什么。',
    coreIdeaEn: 'When evaluating a relationship, observe both what is said and what is consistently done over time.',
    reflectionQuestions: ['对方说过什么？', '实际做了什么？', '两者之间是否长期一致？'],
    counterpoints: ['有些人表达爱的方式是语言而非行动。关键是理解对方的行为语言，而不是只看一种表达方式。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.OBSERVATION,
    sourceReference: '女性成长导师·知识蒸馏 — 看行动不看语言',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-008',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'dynamics',
    title: '关系权益与阶段匹配',
    titleEn: 'Relationship rights match the stage',
    coreIdea: '信任、责任和亲密权益应该随着关系阶段逐步建立，而不是在刚认识时就要求全部。',
    coreIdeaEn: 'Trust, responsibility, and intimacy should build gradually with the relationship stage, not all be demanded at the start.',
    mentorInterpretation: '“到哪一步享受哪一步的权益”不是冷漠，而是保护双方不被过早的承诺和压力绑架。',
    applicationContexts: ['恋爱节奏', '同居讨论', '见家长', '财务合并'],
    reflectionQuestions: ['你们现在的阶段，适合讨论这个话题吗？', '你要求的承诺，对方是否已经有足够的行为基础？'],
    counterpoints: ['关系没有固定进度表。有人发展快，有人发展慢，关键是双方沟通一致。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 关系阶段',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-009',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'independence',
    title: '恋爱不是放弃自己的生活',
    titleEn: 'Romance is not abandoning your own life',
    coreIdea: '亲密关系可以成为人生的一部分，但不应该是人生全部意义的来源。',
    coreIdeaEn: 'Intimacy can be part of life, but it should not be the sole source of meaning.',
    mentorInterpretation: '当一个人把全部生活意义寄托在关系上时，关系本身也会承受过大压力。',
    applicationContexts: ['进入恋爱后疏远朋友', '为伴侣放弃职业机会', '情绪完全依赖伴侣'],
    reflectionQuestions: ['如果没有这段关系，你的生活还有哪些支点？', '你最近一次为自己做的事是什么？'],
    counterpoints: ['亲密关系中自然会有融合和优先级调整。完全独立也可能让伴侣感受不到被需要。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 关系独立',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-010',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'independence',
    title: '不要把整个人生外包给伴侣',
    titleEn: 'Do not outsource your entire life to a partner',
    coreIdea: '伴侣无法也不应承担一个人全部的情绪、社交、经济和人生意义需求。',
    coreIdeaEn: 'A partner cannot and should not bear all of one\'s emotional, social, financial, and existential needs.',
    mentorInterpretation: '把所有鸡蛋放在关系一个篮子里，既是个人风险，也是对伴侣的不合理期待。',
    applicationContexts: ['全职主妇重新评估', '情感依赖', '重大人生决策'],
    reflectionQuestions: ['你的生活里，有哪些需求只依赖这一个人满足？', '如果这种支持暂时不可用，你有哪些替代方案？'],
    counterpoints: ['在特殊时期依赖伴侣是合理的。问题不在于依赖，而在于唯一性和长期性。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 生活外包',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-012',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'red_flags',
    title: '关心与控制需要区分',
    titleEn: 'Distinguish care from control',
    coreIdea: '要求放弃工作、限制正常社交、控制经济资源、持续贬低、用威胁迫使服从等行为，可能是控制而非关心。',
    coreIdeaEn: 'Demands to quit work, restrict social life, control finances, constant belittlement, or threats may signal control, not care.',
    mentorInterpretation: '帮助用户识别行为，不替用户决定是否离开。',
    counterpoints: ['某些文化背景下，关心和控制的外表相似。关键是行为是否尊重对方的自主权和边界。'],
    knowledgeType: KnowledgeType.safety_rule,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SAFETY_RULE,
    sourceReference: '女性成长导师·知识蒸馏 — 关系安全',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-014',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'crisis',
    title: '面对背叛的决策框架',
    titleEn: 'A decision framework for betrayal',
    coreIdea: '面对背叛时，可以从事实、责任归属、修复意愿、重复风险和个人底线五个维度评估是否继续。',
    coreIdeaEn: 'Facing betrayal, evaluate whether to continue based on facts, responsibility, repair willingness, recurrence risk, and personal bottom line.',
    mentorInterpretation: '不替用户决定原谅或离开，而是帮她把这些维度梳理清楚，让决定更清醒。',
    applicationContexts: ['出轨', '重大欺骗', '信任破裂'],
    reflectionQuestions: ['你目前掌握的事实是什么，不包含猜测？', '对方是否承担了责任，还是把过错推给了你？', '如果类似情况再次发生，你能接受吗？'],
    counterpoints: ['有些背叛没有修复空间。框架不是劝和，而是帮助用户不凭单一情绪做决定。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.CONTEXTUAL,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 背叛',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-016',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'stop_loss',
    title: '不因为已经投入而继续消耗',
    titleEn: 'Do not keep investing just because you have invested',
    coreIdea: '时间投入、感情投入和共同经历都很重要，但它们不应该迫使一个人继续一段已经持续伤害自己的关系。',
    coreIdeaEn: 'Time, emotion, and shared history matter, but they should not force someone to stay in a harmful relationship.',
    reflectionQuestions: ['如果今天才认识这个人，你还会选择进入这段关系吗？'],
    counterpoints: ['“止损”不应成为逃避困难的借口。有些关系问题是可修复的，关键是看对方是否有改变意愿和行动。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.CONTEXTUAL,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 止损',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'REL-019',
    domain: KnowledgeDomain.RELATIONSHIPS,
    category: 'manipulation_prevention',
    title: '不用投入绑定别人',
    titleEn: 'Do not use investment to bind others',
    coreIdea: '导师不得建议用户通过金钱、情感债务、威胁、嫉妒或人为制造沉没成本来绑定他人。',
    coreIdeaEn: 'The mentor must never advise creating emotional or financial debt, threats, jealousy, or sunk costs to bind someone.',
    mentorInterpretation: '可以帮助用户识别别人是否正在使用类似方式控制自己。',
    counterpoints: ['识别操纵不等于把所有人都当成操纵者。健康关系中也存在正常投入和相互依赖。'],
    knowledgeType: KnowledgeType.safety_rule,
    safetyClass: SafetyClass.DO_NOT_GENERATE,
    evidenceLevel: EvidenceLevel.SAFETY_RULE,
    sourceReference: '女性成长导师·知识蒸馏 — 沉没成本策略（安全重构）',
    sourceType: 'user_provided_knowledge_base',
  },
  // CAREER (13 nodes)
  {
    id: 'CAREER-001',
    domain: KnowledgeDomain.CAREER,
    category: 'value_creation',
    title: '赚钱来自价值交换',
    titleEn: 'Income comes from value exchange',
    coreIdea: '能够为别人解决问题、提供价值，才能获得相应的经济回报。',
    coreIdeaEn: 'Income follows the ability to solve problems and create value for others.',
    mentorInterpretation: '与其单纯追逐收入数字，不如思考自己正在解决什么问题、为谁解决问题，以及自己的解决方案为什么值得付费。',
    counterpoints: ['价值创造重要，但市场结构、议价能力和资源分配也会影响收入。不能把所有收入差距都归因于个人价值。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 价值创造',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-002',
    domain: KnowledgeDomain.CAREER,
    category: 'positioning',
    title: '价值取决于位置和市场',
    titleEn: 'Value depends on position and market',
    coreIdea: '同样的能力在不同市场、位置和场景中的价值可能差异巨大，选择“站在哪里”有时比“多努力”更重要。',
    coreIdeaEn: 'The same capability can have very different value depending on market, position, and context; where you stand can matter more than how hard you work.',
    mentorInterpretation: '不是否定努力，而是提醒用户同时关注供需关系、平台杠杆和赛道选择。',
    applicationContexts: ['职业选择', '行业转换', '城市选择', '创业赛道'],
    reflectionQuestions: ['你的能力在哪个市场最稀缺？', '如果现在换一个位置，你的价值会如何变化？'],
    counterpoints: ['位置不能替代真实能力。没有硬实力，再好的位置也守不住。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 位置',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-003',
    domain: KnowledgeDomain.CAREER,
    category: 'leverage',
    title: '把时间变成资产',
    titleEn: 'Turn time into assets',
    coreIdea: '把单次出售时间转变为可以重复售卖的产品、内容、IP、客户资产或品牌，能突破收入天花板。',
    coreIdeaEn: 'Converting one-time time sales into repeatedly sellable products, content, IP, customer assets, or brands can break income ceilings.',
    mentorInterpretation: '不是让所有人创业，而是提醒用户思考：自己的时间是否在不断积累资产。',
    applicationContexts: ['副业', '内容创作', '课程产品', '咨询产品化'],
    reflectionQuestions: ['你现在的工作是“卖一次时间换一次钱”，还是在积累可复用资产？', '五年后，你现在的积累还会产生价值吗？'],
    counterpoints: ['并非所有工作都适合产品化。稳定雇佣对一些阶段的人生目标同样有价值。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 时间资产',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-004',
    domain: KnowledgeDomain.CAREER,
    category: 'opportunity',
    title: '信息差带来机会',
    titleEn: 'Information gaps create opportunities',
    coreIdea: '掌握他人尚未掌握的关键信息，可以在职业、商业和投资中创造不对称优势。',
    coreIdeaEn: 'Mastering key information others do not have can create asymmetric advantage in career, business, and investment.',
    mentorInterpretation: '信息差不是投机取巧，而是通过主动学习、观察和进入高质量圈子获得认知领先。',
    applicationContexts: ['求职', '创业', '投资决策', '谈判'],
    reflectionQuestions: ['你现在的关键信息来源是什么？', '如果你进入目标圈子三个月，会知道哪些现在不知道的事？'],
    counterpoints: ['信息差优势正在快速缩小。真正持久的优势还是来自能力和执行，而非单纯信息。'],
    knowledgeType: KnowledgeType.observation,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.OBSERVATION,
    sourceReference: '女性成长导师·知识蒸馏 — 信息差',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-005',
    domain: KnowledgeDomain.CAREER,
    category: 'money_mindset',
    title: '赚长远的钱',
    titleEn: 'Earn long-term money',
    coreIdea: '可持续的收入增长通常来自长期价值积累，而不是短期套利。',
    coreIdeaEn: 'Sustainable income growth usually comes from long-term value accumulation, not short-term arbitrage.',
    mentorInterpretation: '快钱诱惑大，但往往不可持续，且可能消耗信誉和长期机会。',
    applicationContexts: ['职业选择', '创业', '副业', '投资'],
    reflectionQuestions: ['这个选择三年后还成立吗？', '你赚的是红利、运气，还是能力？'],
    counterpoints: ['短期机会也并非完全不可取。关键看它是否能转化为长期资产，还是只是一次性收益。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 长期金钱',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-006',
    domain: KnowledgeDomain.CAREER,
    category: 'leverage',
    title: '善用杠杆',
    titleEn: 'Use leverage wisely',
    coreIdea: '杠杆包括趋势、城市、人脉、产品、复购、团队和科技，善用杠杆可以放大个人产出。',
    coreIdeaEn: 'Leverage includes trends, cities, networks, products, repeat customers, teams, and technology; using leverage can amplify individual output.',
    mentorInterpretation: '没有杠杆的努力增长线性，有杠杆的努力增长指数，但杠杆也放大风险。',
    applicationContexts: ['创业', '职业跃迁', '个人品牌', '团队管理'],
    reflectionQuestions: ['你现在的核心杠杆是什么？', '如果增加一个杠杆，最能放大你现有能力的是哪个？'],
    counterpoints: ['杠杆也会放大失败。在能力不足时加杠杆，可能加速崩塌。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 杠杆',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-007',
    domain: KnowledgeDomain.CAREER,
    category: 'skills',
    title: '技能是长期资产',
    titleEn: 'Skills are long-term assets',
    coreIdea: '真正稳定的职业竞争力来自能力积累。',
    coreIdeaEn: 'Sustainable career competitiveness comes from accumulated abilities.',
    mentorInterpretation: '当短期机会不确定时，提升可迁移能力通常比焦虑结果更有长期价值。',
    counterpoints: ['技能本身不等于收入。市场需求、表达能力和人脉同样决定价值能否兑现。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 技能积累',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-009',
    domain: KnowledgeDomain.CAREER,
    category: 'tradeoff',
    title: '每个选择都有代价',
    titleEn: 'Every choice has a cost',
    coreIdea: '选择一个方向意味着放弃其他方向。',
    coreIdeaEn: 'Choosing one direction means letting go of others.',
    reflectionQuestions: ['我真正想要什么？', '为此我愿意放弃什么？'],
    counterpoints: ['并非所有选择都意味着永久失去。有些选择可以部分兼顾或在不同阶段调整。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 取舍',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-010',
    domain: KnowledgeDomain.CAREER,
    category: 'decision',
    title: '用实验降低职业选择风险',
    titleEn: 'Reduce career choice risk with experiments',
    coreIdea: '重大职业决策可以先通过小规模、低成本的实验获得真实反馈，而不是一次性押注。',
    coreIdeaEn: 'Major career decisions can start with small, low-cost experiments to get real feedback rather than one-time bets.',
    mentorInterpretation: '实验的目的是获取信息，不是立刻成功。失败的小实验也是有效信息。',
    applicationContexts: ['转行', '创业验证', '副业试水', '跳槽'],
    reflectionQuestions: ['如果要验证这个想法，最小的第一步是什么？', '你如何判断实验结果是“信息”而不是“失败”？'],
    counterpoints: ['有些职业机会窗口有限，过度实验可能错过时机。实验需要与决策时限平衡。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 实验',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-011',
    domain: KnowledgeDomain.CAREER,
    category: 'networking',
    title: '向上社交拓展认知边界',
    titleEn: 'Upward networking expands cognitive boundaries',
    coreIdea: '接近拥有更多经验、资源和不同视角的人，可以扩大自己的认知和机会。',
    coreIdeaEn: 'Connecting with people who have more experience, resources, and different perspectives can expand cognition and opportunities.',
    mentorInterpretation: '向上社交的核心不是“被提携”，而是学习他们的思维方式和决策标准。',
    applicationContexts: ['职业早期', '转行', '创业', '晋升'],
    reflectionQuestions: ['你身边有没有人做到了你想做的事？', '你能为比你优秀的人提供什么价值？'],
    counterpoints: ['向上社交若变成功利攀附，反而损害信誉。真正有效的是价值互换和真诚连接。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 向上社交',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-013',
    domain: KnowledgeDomain.CAREER,
    category: 'personal_brand',
    title: '个人品牌是持续价值的可视化',
    titleEn: 'Personal brand is the visualization of sustained value',
    coreIdea: '个人品牌的核心不是包装，而是持续创造价值并在特定人群中建立可信度。',
    coreIdeaEn: 'A personal brand is not packaging; it is consistently creating value and building credibility with a specific audience.',
    mentorInterpretation: '好的个人品牌让用户在需要某类价值时，第一个想到你。',
    applicationContexts: ['自由职业', '专家型职业', '内容创作者', '创业者'],
    reflectionQuestions: ['别人会因为什么记住你？', '你的品牌承诺与你的实际能力是否一致？'],
    counterpoints: ['过早打造品牌而能力跟不上，会加速信任崩塌。品牌应该是能力溢出后的自然结果。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 个人品牌',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-016',
    domain: KnowledgeDomain.CAREER,
    category: 'productivity',
    title: '聚焦而非分散',
    titleEn: 'Focus rather than scatter',
    coreIdea: '在有限时间内，集中资源把一件事做透，通常比同时做很多事更容易建立优势。',
    coreIdeaEn: 'Within limited time, concentrating resources to do one thing deeply usually builds advantage faster than doing many things at once.',
    mentorInterpretation: '机会很多时，选择的难度不在“做什么”，而在“不做什么”。',
    applicationContexts: ['职业发展', '副业选择', '技能学习', '创业方向'],
    reflectionQuestions: ['如果你只能保留一个目标，会是哪个？', '你现在同时推进的事，哪些其实可以舍弃？'],
    counterpoints: ['过早聚焦可能错过机会。探索期需要一定广度，聚焦应建立在充分尝试之后。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 聚焦',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'CAREER-033',
    domain: KnowledgeDomain.CAREER,
    category: 'decision',
    title: '行动推动决策',
    titleEn: 'Action drives decision',
    coreIdea: '在信息不足的情况下，可以设计可验证的行动，通过反馈推动下一步决策。',
    coreIdeaEn: 'When information is insufficient, design verifiable actions and use feedback to drive the next decision.',
    counterpoints: ['行动不能替代战略性思考。无方向地“先干起来”可能浪费资源并增加沉没成本。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 行动推动决策',
    sourceType: 'user_provided_knowledge_base',
  },
  // LIFE DECISIONS (9 nodes)
  {
    id: 'DEC-001',
    domain: KnowledgeDomain.LIFE_DECISIONS,
    category: 'goal',
    title: '从目标倒推行动',
    titleEn: 'Work backwards from goals',
    coreIdea: '先明确想要的结果，再思考应该采取什么行动。',
    coreIdeaEn: 'Clarify the desired outcome before deciding what actions to take.',
    counterpoints: ['目标可能随认知和环境变化。过度执着初始目标，可能错过更好的路径。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 目标导向',
    sourceType: 'derived_from_source',
  },
  {
    id: 'DEC-002',
    domain: KnowledgeDomain.LIFE_DECISIONS,
    category: 'interpretation',
    title: '区分事实与解读',
    titleEn: 'Separate facts from interpretation',
    coreIdea: '同样的事实可以有很多解读，先把“发生了什么”与“我认为这意味着什么”分开，能避免过度反应。',
    coreIdeaEn: 'The same facts can have many interpretations; separating "what happened" from "what I think it means" prevents overreaction.',
    mentorInterpretation: '很多痛苦来自解读，而不是事实本身。帮助用户回到可验证的事实上。',
    applicationContexts: ['冲突后复盘', '被批评', '关系危机', '职场误解'],
    reflectionQuestions: ['你能用一句话描述客观发生的事实吗？', '你的解读里，有哪些是假设，哪些是证据？'],
    counterpoints: ['过度强调事实可能压抑真实情绪。事实与解读都需要被看见，但不应混为一谈。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 事实与解读',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'DEC-003',
    domain: KnowledgeDomain.LIFE_DECISIONS,
    category: 'expectation',
    title: '预期决定心态',
    titleEn: 'Expectations shape mindset',
    coreIdea: '对结果、他人或自己的预期如果不合理，会直接影响情绪、行为和关系质量。',
    coreIdeaEn: 'Unreasonable expectations of outcomes, others, or oneself directly affect emotions, behavior, and relationship quality.',
    mentorInterpretation: '预期管理不是降低标准，而是让预期与可控因素对齐。',
    applicationContexts: ['新工作', '恋爱初期', '重大决定', '长期目标'],
    reflectionQuestions: ['你的预期是基于什么信息建立的？', '如果结果不如预期，你准备如何解释它？'],
    counterpoints: ['过度降低预期可能削弱动力。健康预期是有根据的、可调整的，而不是悲观。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 预期管理',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'DEC-004',
    domain: KnowledgeDomain.LIFE_DECISIONS,
    category: 'action',
    title: '用行动减少不确定性',
    titleEn: 'Reduce uncertainty through action',
    coreIdea: '某些问题无法仅通过思考解决，可以通过小规模、可控行动获得新的信息。',
    coreIdeaEn: 'Some problems cannot be solved by thinking alone; small, controlled actions generate new information.',
    counterpoints: ['行动不是万能药。有些问题需要更多信息或他人支持，盲目行动可能制造新问题。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 行动产生信息',
    sourceType: 'derived_from_source',
  },
  {
    id: 'DEC-005',
    domain: KnowledgeDomain.LIFE_DECISIONS,
    category: 'stop_loss',
    title: '止损是承认错误的能力',
    titleEn: 'Stop loss is the ability to admit mistakes',
    coreIdea: '当继续投入的代价明显高于停止的代价时，及时止损比继续消耗更需要勇气。',
    coreIdeaEn: 'When the cost of continuing clearly exceeds the cost of stopping, cutting losses takes more courage than persisting.',
    mentorInterpretation: '止损不是失败，而是把有限资源重新分配到更有价值的地方。',
    applicationContexts: ['错误关系', '亏损投资', '无效职业路径', '沉没成本困境'],
    reflectionQuestions: ['如果这是别人的处境，你会建议她继续还是停止？', '继续一年的真实代价是什么？'],
    counterpoints: ['有些困难需要坚持。止损不是遇到困难就放弃，而是基于成本和收益的理性判断。'],
    knowledgeType: KnowledgeType.principle,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.SOURCE_PRINCIPLE,
    sourceReference: '女性成长导师·知识蒸馏 — 止损',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'DEC-006',
    domain: KnowledgeDomain.LIFE_DECISIONS,
    category: 'sunk_cost',
    title: '不因为已经投入而被迫继续',
    titleEn: 'Sunk costs should not force continuation',
    coreIdea: '已经投入的时间、金钱或情感，不应该自动成为继续错误选择的理由。',
    coreIdeaEn: 'Time, money, or emotion already invested should not automatically justify continuing a poor choice.',
    counterpoints: ['沉没成本不是唯一考虑。有时继续是因为未来仍有价值，而不是为了挽回过去。'],
    knowledgeType: KnowledgeType.concept,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 沉没成本',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'DEC-007',
    domain: KnowledgeDomain.LIFE_DECISIONS,
    category: 'decision_making',
    title: '可逆决定快速做',
    titleEn: 'Make reversible decisions quickly',
    coreIdea: '如果决定可以低成本撤回，不必追求完全确定，可以更快地行动获取反馈。',
    coreIdeaEn: 'If a decision can be reversed at low cost, you do not need full certainty; act faster to get feedback.',
    mentorInterpretation: '很多人把可逆决定当成不可逆决定来做，导致拖延。',
    applicationContexts: ['试错', '新产品', '新爱好', '短期选择'],
    reflectionQuestions: ['这个决定最坏能坏到什么程度？', '撤销它的成本有多高？'],
    counterpoints: ['即使可逆，频繁试错也会消耗注意力和信誉。快速决策不等于轻率决策。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 可逆决策',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'DEC-008',
    domain: KnowledgeDomain.LIFE_DECISIONS,
    category: 'decision_making',
    title: '不可逆决定慢思考',
    titleEn: 'Think slowly on irreversible decisions',
    coreIdea: '难以撤回的重大决定值得收集更多信息、咨询多元视角并充分考虑后果。',
    coreIdeaEn: 'Major decisions that are hard to undo deserve more information, diverse perspectives, and careful consideration of consequences.',
    mentorInterpretation: '对不可逆决定的谨慎不是优柔寡断，而是对长期代价的尊重。',
    applicationContexts: ['结婚', '生育', '移民', '买房', '职业大转型'],
    reflectionQuestions: ['十年后回头看，这个决定的哪些部分会最重要？', '有哪些信息你目前还没有但可以获得？'],
    counterpoints: ['信息永远不可能完备。过度收集信息也会导致决策瘫痪，需要设定截止日期。'],
    knowledgeType: KnowledgeType.framework,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 不可逆决策',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'DEC-010',
    domain: KnowledgeDomain.LIFE_DECISIONS,
    category: 'evaluation',
    title: '区分好决策与好结果',
    titleEn: 'Distinguish good decisions from good outcomes',
    coreIdea: '好决策可能因运气产生坏结果，坏决策也可能因运气产生好结果。复盘时应先评价决策过程，再评价结果。',
    coreIdeaEn: 'A good decision can produce a bad result due to luck, and a bad decision can produce a good result. Review the decision process before the outcome.',
    mentorInterpretation: '学会区分“我是否做了一个明智的决定”和“事情是否按我期望发展”，能减少非理性的自责或自满。',
    applicationContexts: ['职业选择复盘', '投资结果', '关系决定'],
    reflectionQuestions: ['如果重来一次，你还会做同样的决定吗？', '结果中有多少是你能控制的，多少是运气？'],
    counterpoints: ['长期结果仍然是衡量决策质量的重要依据。不能只看过程而忽视结果反馈。'],
    knowledgeType: KnowledgeType.concept,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 决策与结果',
    sourceType: 'user_provided_knowledge_base',
  },
  // COMMUNICATION (5 nodes)
  {
    id: 'COM-001',
    domain: KnowledgeDomain.COMMUNICATION,
    category: 'listening',
    title: '倾听大于表达',
    titleEn: 'Listen more than speak',
    coreIdea: '在沟通中先理解对方真正想表达什么，再决定如何回应。',
    coreIdeaEn: 'In communication, first understand what the other person is really saying before responding.',
    counterpoints: ['倾听不是无限忍耐。如果对方持续不尊重，表达和保护自己同样重要。'],
    knowledgeType: KnowledgeType.communication,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 沟通原则',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'COM-002',
    domain: KnowledgeDomain.COMMUNICATION,
    category: 'expression',
    title: '表达自己的感受和需求',
    titleEn: 'Express feelings and needs',
    coreIdea: '表达不满时，聚焦于自己的感受和需求，而不是指责对方的人格，更容易被听进去。',
    coreIdeaEn: 'When expressing dissatisfaction, focus on your own feelings and needs rather than blaming the other person\'s character; it is more likely to be heard.',
    mentorInterpretation: '“你总是……”会触发防御，而“当……发生时，我感到……，因为我需要……”更开放。',
    applicationContexts: ['亲密关系冲突', '职场反馈', '家庭矛盾'],
    reflectionQuestions: ['你想表达的核心需求是什么？', '如果对方用同样方式对你说话，你会如何反应？'],
    counterpoints: ['非暴力表达不是压抑愤怒或委曲求全。表达需求的同时也要维护边界。'],
    knowledgeType: KnowledgeType.communication,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 非暴力沟通',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'COM-003',
    domain: KnowledgeDomain.COMMUNICATION,
    category: 'clarification',
    title: '先确认，再下结论',
    titleEn: 'Confirm before concluding',
    coreIdea: '很多冲突来自把猜测当成事实，先询问对方的真实意图，可以避免不必要的误解。',
    coreIdeaEn: 'Much conflict comes from treating guesses as facts; asking about the other person\'s real intent first can prevent unnecessary misunderstanding.',
    mentorInterpretation: '好奇心先于判断。一句“我想确认一下你的意思”常常能化解僵局。',
    applicationContexts: ['关系误会', '职场沟通', '家庭争执'],
    reflectionQuestions: ['你现在的判断有多少是猜测？', '你有没有给对方解释的机会？'],
    counterpoints: ['过度询问也可能变成回避问题。确认之后仍然需要面对真实差异。'],
    knowledgeType: KnowledgeType.communication,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 确认意图',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'COM-004',
    domain: KnowledgeDomain.COMMUNICATION,
    category: 'difficult_conversations',
    title: '艰难对话的结构',
    titleEn: 'Structure difficult conversations',
    coreIdea: '高难度对话可以拆解为：陈述事实、表达感受、说明需求、提出请求，并给对方回应空间。',
    coreIdeaEn: 'Difficult conversations can be structured as: state facts, express feelings, explain needs, make a request, and leave room for response.',
    mentorInterpretation: '结构不是为了控制结果，而是让对话在混乱中保持清晰。',
    applicationContexts: ['分手谈话', '薪资谈判', '边界设立', '道歉'],
    reflectionQuestions: ['这次对话你最想达成什么？', '你能够接受的最差结果是什么？'],
    counterpoints: ['结构不能保证对方配合。对方可能拒绝沟通，这时保护自己和选择退出同样重要。'],
    knowledgeType: KnowledgeType.communication,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 艰难对话',
    sourceType: 'user_provided_knowledge_base',
  },
  {
    id: 'COM-005',
    domain: KnowledgeDomain.COMMUNICATION,
    category: 'boundaries',
    title: '清晰表达边界',
    titleEn: 'Express boundaries clearly',
    coreIdea: '沟通边界时，可以说明事实、自己的需求、边界本身以及后续行动。',
    coreIdeaEn: 'When stating boundaries, describe the facts, your needs, the boundary, and your follow-up action.',
    counterpoints: ['清晰表达边界不等于对方会接受。对方有拒绝的权利，你也有坚持和维护边界的权利。'],
    knowledgeType: KnowledgeType.communication,
    safetyClass: SafetyClass.SAFE,
    evidenceLevel: EvidenceLevel.FRAMEWORK,
    sourceReference: '女性成长导师·知识蒸馏 — 边界沟通',
    sourceType: 'user_provided_knowledge_base',
  },
];

const seedRelations: any[] = [
  { sourceNodeId: 'SELF-001', targetNodeId: 'SELF-020', relationType: RelationType.SUPPORTS, weight: 1.0 },
  { sourceNodeId: 'SELF-001', targetNodeId: 'DEC-001', relationType: RelationType.RELATED, weight: 0.9 },
  { sourceNodeId: 'SELF-002', targetNodeId: 'SELF-003', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'SELF-003', targetNodeId: 'REL-005', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'SELF-004', targetNodeId: 'SELF-020', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'SELF-004', targetNodeId: 'REL-005', relationType: RelationType.APPLIES_TO, weight: 0.8 },
  { sourceNodeId: 'SELF-005', targetNodeId: 'SELF-006', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'SELF-007', targetNodeId: 'CAREER-007', relationType: RelationType.SUPPORTS, weight: 1.0 },
  { sourceNodeId: 'SELF-008', targetNodeId: 'SELF-010', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'SELF-009', targetNodeId: 'DEC-004', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'SELF-010', targetNodeId: 'DEC-004', relationType: RelationType.RELATED, weight: 0.9 },
  { sourceNodeId: 'SELF-011', targetNodeId: 'COM-005', relationType: RelationType.APPLIES_TO, weight: 0.9 },
  { sourceNodeId: 'SELF-011', targetNodeId: 'REL-012', relationType: RelationType.APPLIES_TO, weight: 0.8 },
  { sourceNodeId: 'SELF-013', targetNodeId: 'COM-005', relationType: RelationType.APPLIES_TO, weight: 1.0 },
  { sourceNodeId: 'REL-001', targetNodeId: 'REL-007', relationType: RelationType.SUPPORTS, weight: 0.8 },
  { sourceNodeId: 'REL-001', targetNodeId: 'REL-002', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'REL-002', targetNodeId: 'CAREER-009', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'REL-003', targetNodeId: 'DEC-003', relationType: RelationType.RELATED, weight: 0.9 },
  { sourceNodeId: 'REL-006', targetNodeId: 'REL-016', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'REL-007', targetNodeId: 'REL-012', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'REL-008', targetNodeId: 'REL-006', relationType: RelationType.PREREQUISITE, weight: 0.8 },
  { sourceNodeId: 'REL-009', targetNodeId: 'SELF-004', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'REL-009', targetNodeId: 'REL-005', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'REL-010', targetNodeId: 'REL-009', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'REL-014', targetNodeId: 'DEC-005', relationType: RelationType.APPLIES_TO, weight: 0.9 },
  { sourceNodeId: 'REL-016', targetNodeId: 'DEC-006', relationType: RelationType.RELATED, weight: 1.0 },
  { sourceNodeId: 'CAREER-001', targetNodeId: 'CAREER-007', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'CAREER-002', targetNodeId: 'CAREER-001', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'CAREER-003', targetNodeId: 'CAREER-007', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'CAREER-003', targetNodeId: 'CAREER-006', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'CAREER-004', targetNodeId: 'CAREER-006', relationType: RelationType.SUPPORTS, weight: 0.8 },
  { sourceNodeId: 'CAREER-005', targetNodeId: 'CAREER-003', relationType: RelationType.SUPPORTS, weight: 0.8 },
  { sourceNodeId: 'CAREER-006', targetNodeId: 'CAREER-016', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'CAREER-009', targetNodeId: 'DEC-001', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'CAREER-010', targetNodeId: 'CAREER-033', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'CAREER-011', targetNodeId: 'CAREER-013', relationType: RelationType.SUPPORTS, weight: 0.8 },
  { sourceNodeId: 'CAREER-033', targetNodeId: 'DEC-004', relationType: RelationType.SUPPORTS, weight: 1.0 },
  { sourceNodeId: 'DEC-001', targetNodeId: 'DEC-003', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'DEC-002', targetNodeId: 'DEC-003', relationType: RelationType.SUPPORTS, weight: 0.8 },
  { sourceNodeId: 'DEC-003', targetNodeId: 'DEC-001', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'DEC-004', targetNodeId: 'DEC-006', relationType: RelationType.CONTRASTS, weight: 0.7 },
  { sourceNodeId: 'DEC-005', targetNodeId: 'DEC-006', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'DEC-005', targetNodeId: 'REL-016', relationType: RelationType.RELATED, weight: 0.9 },
  { sourceNodeId: 'DEC-007', targetNodeId: 'DEC-008', relationType: RelationType.CONTRASTS, weight: 0.8 },
  { sourceNodeId: 'DEC-007', targetNodeId: 'DEC-004', relationType: RelationType.SUPPORTS, weight: 0.9 },
  { sourceNodeId: 'DEC-010', targetNodeId: 'DEC-006', relationType: RelationType.RELATED, weight: 0.8 },
  { sourceNodeId: 'COM-001', targetNodeId: 'COM-002', relationType: RelationType.PREREQUISITE, weight: 0.8 },
  { sourceNodeId: 'COM-001', targetNodeId: 'REL-007', relationType: RelationType.SUPPORTS, weight: 0.8 },
  { sourceNodeId: 'COM-003', targetNodeId: 'COM-002', relationType: RelationType.SUPPORTS, weight: 0.8 },
  { sourceNodeId: 'COM-004', targetNodeId: 'COM-005', relationType: RelationType.APPLIES_TO, weight: 0.9 },
];

async function main() {
  console.log('Seeding HerBecoming knowledge base...');

  // Clean existing seed data
  await prisma.knowledgeRelation.deleteMany({});
  await prisma.knowledgeEmbedding.deleteMany({});
  await prisma.knowledgeNode.deleteMany({});

  // Insert nodes
  for (const node of seedKnowledgeNodes) {
    await prisma.knowledgeNode.create({ data: node });
  }
  console.log(`Inserted ${seedKnowledgeNodes.length} knowledge nodes.`);

  // Insert relations
  for (const rel of seedRelations) {
    await prisma.knowledgeRelation.create({ data: rel });
  }
  console.log(`Inserted ${seedRelations.length} knowledge relations.`);

  // Insert dummy embeddings using pgvector SQL (random unit vectors)
  for (const node of seedKnowledgeNodes) {
    const arr = Array.from({ length: 1536 }, () => (Math.random() * 2 - 1).toFixed(6)).join(',');
    const id = crypto.randomUUID();
    await prisma.$executeRawUnsafe(
      `INSERT INTO knowledge_embeddings (id, "knowledgeNodeId", embedding, "embeddingLang", model)
       VALUES ('${id}', '${node.id}', '[${arr}]'::vector, 'zh', 'text-embedding-3-small')`
    );
  }
  console.log(`Inserted ${seedKnowledgeNodes.length} placeholder embeddings.`);

  // Insert mentor persona v1.0
  await prisma.mentorPersona.upsert({
    where: { version: 'v1.0' },
    update: {},
    create: {
      version: 'v1.0',
      isActive: true,
      identity: {
        role: 'female_growth_mentor',
        style: 'rational_warm',
        personality: ['clear', 'confident', 'encouraging', 'grounded', 'independent', 'thoughtful'],
      },
      philosophy: [
        { id: 'P1', text: 'Help the user think, not decide for her.' },
        { id: 'P2', text: 'Complex problems do not need artificially simple answers.' },
        { id: 'P3', text: 'The mentor may respectfully disagree with the user.' },
        { id: 'P4', text: 'Disagree with the idea, not the person.' },
        { id: 'P5', text: 'Be positive, not blindly optimistic.' },
        { id: 'P6', text: 'Take difficulties seriously.' },
        { id: 'P7', text: 'Preserve user agency.' },
      ],
      communication: {
        tone: { positive: true, constructive: true, respectful: true, nonjudgmental: true },
        avoid: ['preaching', 'shaming', 'excessive_flattery', 'fear_mongering', 'absolute_commands'],
      },
      decisionPhilosophy: [
        'preserve_user_agency',
        'clarify_tradeoffs',
        'distinguish_fact_and_interpretation',
        'encourage_action',
        'accept_uncertainty',
      ],
      reasoningRules: ['MR-01', 'MR-02', 'MR-03', 'MR-04', 'MR-05', 'MR-06', 'MR-07', 'MR-08', 'MR-09', 'MR-10'],
      systemPrompt: `You are the HerBecoming Mentor, an original AI mentor for women navigating work, relationships, self-discovery, and life decisions.

You have learned from the HerBecoming Knowledge Base. Your role is not to retrieve and repeat knowledge, but to reason through the user's situation using the principles, frameworks, observations, and perspectives it contains.

Rules:
1. Understand the user's actual situation first.
2. Automatically identify primary and secondary domains.
3. Retrieve multiple related knowledge units when appropriate.
4. Do not mention internal knowledge IDs.
5. Do not mechanically quote the knowledge base.
6. Do not invent principles that contradict the knowledge base.
7. You may disagree with the user respectfully.
8. Never make major life decisions on behalf of the user.
9. Responses must be constructive, respectful, and forward-looking.
10. Never encourage manipulation, coercion, revenge, or harmful behavior.
11. When source knowledge contains manipulative strategies, reinterpret the underlying observation in a healthy way.
12. When the knowledge base does not provide sufficient basis, explicitly acknowledge the limitation.
13. Respond in the same language as the user's main input.`,
    },
  });
  console.log('Inserted active mentor persona v1.0.');

  console.log('Seed complete.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
